### ISSUE TITLE
Chat/Rewards not connecting to server

### ISSUE THREAD

**Issue by sameethan1** [jayther/hackathon-overlay-minigame#1]
I've been using the minigame for a few months now on stream, but suddenly as of a week ago, my chat can't spawn fighters anymore. I was messing around with it today, even did a fresh reinstalled, yet still nothing fixed it...
The debug players spawn fine, it's just the connection to chat itself isn't working/when looking at the rewards tab it shows Unknown even after just setting up basic rewards.
Hope you can help me out, my chat and I really enjoy these fighters compared to others, thank you!

![Capture](https://user-images.githubusercontent.com/53244457/146653349-65515e16-e074-4c06-9c03-f153277c0fdd.JPG)

**Comment by jayther** [comment]
Hey @sameethan1 , first off, thanks for using my hackathon project!

I am not sure what the issue could be, but here are some steps to try to resolve connecting to chat:
* Check if your chat verification settings or "followers only mode" are preventing your chat bot account from sending messages.
* Reauth:  Delete `.usertokens.json` and `.chatbottokens.json`, auth both streamer account and chat bot account, then restart the server.
* Try using a different Twitch account for the chat bot to see if that connects.
* Try making another Twitch Developer App and use those app secrets.

Also, I think there were issues with some Twitch services around that time, so there may have been weird tokens or state happening, so clearing the token files may fix some weird states.

As for the "Unknown" in the reward map, it's is a bug with the control panel when the server just started. Refreshing the control panel should fix and show the proper redemption names.

**Comment by sameethan1** [comment]
Hi, sorry for the LATE reply, I've been busy with work and just got around to being able to test the solutions...
- I double checked verification and followers only are off, along with any other weird stuff on that page.
- I have reconnected usertoken and chatbot multiple times
- I made a new twitch account to use as chatbot
- I made a new dev app with secrets

Sadly, none of those fixed the issue of allowing the server to connect to chat/read they are using channel points to spawn fighters.

**Comment by jayther** [comment]
Hey, no worries!

There was a similar issue soon after yours was first posted, and the solution seems to be to download ngrok, create an account, and set the authtoken. I updated the readme to include the ngrok portion: https://github.com/jayther/hackathon-overlay-minigame#ngrok

Let me know if this solves it for you.

**Comment by sameethan1** [comment]
After downloading and running ngrok once, it did fix the issue!
I was getting a new error about "custom reward created by different client/channel points not available for broadcaster" but I just remade the rewards and it running smoothly again.

I was wondering though, if it's possible to add a despawn fighter reward option?
My chat enjoys watching their duels and we have a little challenge to see who can get to a 10kill streak first. Since people come and go, I like giving them the option to despawn their fighters, so they don't miss the battles they are involved in. Right now I have to do that manually though on the control panel, so thought I'd ask if it's possible to add an auto feature...

Otherwise, Thank You for helping to resolve the connection issue, glad to be using it again!

**Comment by jayther** [comment]
Great to hear it works again!

As for the "despawn fighter reward" option, I could have it as a reward or chat option (similar to the `!char` and `!gender` commands/rewards), although I'm not sure when I will be able to add this feature. When it is added, though, I'll be sure to tag you! :)
